version: '2'

services:
  snort: # Domain name of container
    image: linton/docker-snort:latest # image of the container
    restart: unless-stopped # Operation Policy
    container_name: snort # Name of the container
    hostname: snort # hostname
    privileged: true # Give the container the permission to manipulate the host
    networks: # the network this container attached to
      - devops

  jenkins:
    image: jenkins/jenkins:2.60.3
    restart: unless-stopped
    container_name: jenkins
    hostname: jenkins
    privileged: true
    ports: #Expose port to host network
      - 8089:8080
      - 50000:50000
    networks:
      - devops
    
  logstash:
    image: logstash/logstash:7.6.1
    restart: unless-stopped
    container_name: logstash
    hostname: logstash
    privileged: true
    networks: 
      - devops

  elasticsearch:
    image: elasticsearch/elasticsearch:7.6.1
    restart: unless-stopped
    container_name: elasticsearch
    hostname: elasticsearch
    ports: # Expose port to host network
      - 9200:9200
      - 9300:9300
    environment: # shell variables
      - discovery.type=single-node
    networks:
      - devops

  kibana:
    image: kibana/kibana:7.6.1
    restart: unless-stopped
    container_name: kibana
    hostname: kibana
    ports: #Expose port to host network
      - 5601:5601
    networks:
      - devops

networks: # Define our network here
  devops:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000 # Configure mtu

